### ISSUE TITLE
 No file named pycocoevalcap.py

### ISSUE THREAD

**Issue by ZhangC2** [zhangludl/code-and-dataset-for-CapSal#5]
I follow the guidance, and run test_capsal.py .

**Comment by zhangludl** [comment]
Down load the coco evaluation tool at https://pan.baidu.com/s/1mRN_qV7X8ZLUeuARQY3EwQ

**Comment by zhangludl** [comment]
Please refer to the comments in eval_cap.py. 'Down load the coco evaluation tool at https://pan.baidu.com/s/1mRN_qV7X8ZLUeuARQY3EwQ
'. You should also install the coco evaluation toolkit from their official website
